on:
  workflow_dispatch:

jobs:
  build-linux-shaderc-arm:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Install prereq
        run: |
          sudo apt update
          sudo apt install -y --fix-missing git curl cmake clang ninja-build python3 wget build-essential checkinstall zlib1g-dev libssl-dev
      - uses: actions/checkout@v5
        with:
          repository: google/shaderc
          path: shaderc
          ref: v2025.5
          submodules: recursive
      - name: Compile shaderc
        run: |
          wget -nv https://github.com/Kitware/CMake/releases/download/v4.2.1/cmake-4.2.1-linux-aarch64.sh
          chmod +x cmake-4.2.1-linux-aarch64.sh
          mkdir cmake
          ./cmake-4.2.1-linux-aarch64.sh --prefix=$(realpath ./cmake) <<EOF
          y
          n
          EOF
          export PATH=$(realpath ./cmake/bin):$PATH
          wget -nv https://static.crates.io/crates/glslang-sys/glslang-sys-0.7.0%2B1062752.crate
          tar -xvf glslang-sys-0.7.0+1062752.crate
          cd shaderc
          ./utils/git-sync-deps
          rm -rf third_party/glslang/
          cp -r ../glslang-sys-0.7.0+1062752/native/glslang third_party/
          cmake -GNinja -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=../linux-shaderc-arm -DCMAKE_BUILD_TYPE=Release -DSHADERC_SKIP_TESTS=ON -DSHADERC_SKIP_EXAMPLES=ON -DENABLE_GLSLANG_BINARIES=OFF -DENABLE_HLSL=ON -DENABLE_OPT=ON .
          ninja
          ninja install
          cd ..
      - uses: actions/upload-artifact@v4
        with:
          name: linux-shaderc-arm
          path: linux-shaderc-arm
