on:
  workflow_dispatch:

jobs:
  build-linux-app-lite:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm-slim
    steps:
      - name: Install prereq
        run: |
          apt update
          apt install -y --fix-missing git curl cmake clang ninja-build meson python3 wget build-essential checkinstall zlib1g-dev libssl-dev gh vim nasm
      - uses: actions/checkout@v5
        with:
          path: ntrviewer-hr
      - name: Get artifact
        id: artifact-name
        run: |
          RUN=$(gh run list --repo ${{ github.repository }} -L 1 -w linux_sdl.yml --json databaseId -q '.[0].databaseId')
          gh run download --repo ${{ github.repository }} $RUN -n linux-sdl -D linux-sdl
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Compile NTRViewer-HR
        run: |
          ln -s ../../linux-sdl/include/SDL3 ntrviewer-hr/include/SDL3
          mkdir ntrviewer-hr/lib
          ln -s ../../linux-sdl/lib/libSDL3.a ntrviewer-hr/lib/libSDL3.a
          cd ntrviewer-hr
          make -j$(nproc) LITE=1 STATIC_SDL=1
          cd ..
          mkdir NTRViewer-HR-Lite-Linux-x64
          cp ntrviewer-hr/ntrviewer NTRViewer-HR-Lite-Linux-x64/
          cp ntrviewer-hr/ntrviewer-x11.sh NTRViewer-HR-Lite-Linux-x64/
          tar -czvf NTRViewer-HR-Lite-Linux-x64.tar.gz NTRViewer-HR-Lite-Linux-x64/*
      - uses: actions/upload-artifact@v4
        with:
          name: NTRViewer-HR-Lite-Linux-x64.tar.gz
          path: NTRViewer-HR-Lite-Linux-x64.tar.gz
