on:
  workflow_dispatch:

jobs:
  build-linux-rashader:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm-slim
    steps:
      - uses: actions/checkout@v5
        with:
          path: ntrviewer-hr
      - uses: actions/checkout@v5
        with:
          repository: SnowflakePowered/librashader
          path: librashader
          ref: librashader-v0.12.0
      - name: Compile librashader
        run: |
          apt update
          apt install -y --fix-missing curl gcc g++ clang
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain none
          . "$HOME/.cargo/env"
          ntrviewer-hr/linux-scripts/compile-rashader.sh
          mkdir -p linux-rashader/include
          ln -s ../../librashader/include/librashader.h linux-rashader/include/librashader.h
          mkdir linux-rashader/lib
          ln -s ../../librashader/target/optimized/liblibrashader_capi.a linux-rashader/lib/librashader.a
      - uses: actions/upload-artifact@v4
        with:
          name: linux-rashader
          path: linux-rashader
