on:
  workflow_dispatch:

jobs:
  build-macos-package:
    runs-on: macos-latest
    steps:
      - name: Compile rcodesign
        run: |
          cargo install --git https://github.com/indygreg/apple-platform-rs --branch main --bin rcodesign apple-codesign
          ln -s $(which rcodesign) .
      - uses: actions/upload-artifact@v4
        with:
          name: rcodesign
          path: rcodesign
          compression-level: 0
