on:
  workflow_dispatch:

env:
  VULKAN_VERSION: 1.4.321.0

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
        with:
          path: ntrviewer-hr
      - name: Get artifact
        id: artifact-name
        run: |
          ARTIFACT_NAME=$(gh run list --repo ${{ github.repository }} -L 1 -w rashader.yml --json databaseId -q '.[0].databaseId')
          echo $ARTIFACT_NAME
          echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v5
        with:
          name: rashader
          path: rashader
          github-token: ${{ secrets.GH_PAT }}
          run-id: ${{ steps.artifact-name.outputs.ARTIFACT_NAME }}
      - name: Compile NTRViewer-HR
        run: |
          ntrviewer-hr/macos-scripts/install-reqs.sh
          ln -s ../../rashader/include/librashader.h ntrviewer-hr/include/librashader.h
          mkdir ntrviewer-hr/lib
          ln -s ../../rashader/target/optimized/liblibrashader_capi.dylib ntrviewer-hr/lib/librashader.dylib
          pushd ntrviewer-hr
          make -j$(sysctl -n hw.logicalcpu)
          popd
      - name: Package NTRViewer-HR
        run: |
          mkdir macos
          pushd macos
          ../ntrviewer-hr/macos-scripts/complete-deps.sh
          popd
      - uses: actions/upload-artifact@v4
        with:
          name: macos
          path: macos
