on:
  workflow_dispatch:

jobs:
  build-windows-rashader:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          path-type: inherit
          update: true
      - uses: actions/checkout@v5
        with:
          path: ntrviewer-hr
      - uses: actions/checkout@v5
        with:
          repository: xzn/librashader
          path: librashader
      - name: Compile librashader
        run: |
          rustup toolchain install nightly-2025-08-08-gnu
          rustup default nightly-2025-08-08-gnu
          pushd librashader/librashader-capi
          cargo build --profile optimized --no-default-features --features runtime-opengl,runtime-d3d11,runtime-vulkan
          popd
          mkdir -p windows-rashader/include
          ln -s ../../librashader/include/librashader.h windows-rashader/include/librashader.h
          mkdir windows-rashader/lib
          ln -s ../../librashader/target/optimized/liblibrashader_capi.a windows-rashader/lib/librashader.a
      - uses: actions/upload-artifact@v4
        with:
          name: windows-rashader
          path: windows-rashader
