on:
  workflow_dispatch:

jobs:
  build-windows-shaderc:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          path-type: minimal
          update: true
          install: |
            wget
            git
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-python
      - uses: actions/checkout@v5
        with:
          repository: google/shaderc
          path: shaderc
          ref: v2025.5
          submodules: recursive
      - name: Compile shaderc
        run: |
          wget -nv https://static.crates.io/crates/glslang-sys/glslang-sys-0.7.0%2B1062752.crate
          tar -xvf glslang-sys-0.7.0+1062752.crate
          pushd shaderc
          ./utils/git-sync-deps
          rm -rf third_party/glslang/
          cp -r ../glslang-sys-0.7.0+1062752/native/glslang third_party/
          cmake -GNinja -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=Release -DSHADERC_SKIP_TESTS=ON -DSHADERC_SKIP_EXAMPLES=ON -DENABLE_GLSLANG_BINARIES=OFF -DENABLE_HLSL=ON -DENABLE_OPT=ON .
          ninja
          ninja install
          popd
          mkdir windows-shaderc
          ln -s ../install/lib/libshaderc_combined.a windows-shaderc/
      - uses: actions/upload-artifact@v4
        with:
          name: windows-shaderc
          path: windows-shaderc
